#define WHERE                            1
#define NOT                              2
#define IS                               3
#define OCCUR                            4
#define GT                               5
#define GTEQ                             6
#define LT                               7
#define LTEQ                             8
#define NEQ                              9
#define COUNT                           10
#define FIRST                           11
#define COMMA                           12
#define PLUS                            13
#define MINUS                           14
#define AMPERSAND                       15
#define TIMES                           16
#define DIVIDE                          17
#define POWER                           18
#define SIN                             19
#define COS                             20
#define OF                              21
#define WRITE                           22
#define SEMICOLON                       23
#define TIME                            24
#define TRACE                           25
#define IDENTIFIER                      26
#define ASSIGN                          27
#define LSPAR                           28
#define NUMTOKEN                        29
#define RSPAR                           30
#define LPAR                            31
#define RPAR                            32
#define BOOLTOKEN                       33
#define IT                              34
#define NOW                             35
#define NULLTOKEN                       36
#define STRTOKEN                        37
#define TIMETOKEN                       38
#define LIST                            39
#define NUMBER                          40
#define GREATER                         41
#define THAN                            42
#define OR                              43
#define EQUAL                           44
#define LESS                            45
#define AFTER                           46
#define BEFORE                          47
#define WITHIN                          48
#define TO                              49
