#define COUNT                            1
#define FIRST                            2
#define COMMA                            3
#define AMPERSAND                        4
#define PLUS                             5
#define MINUS                            6
#define TIMES                            7
#define DIVIDE                           8
#define POWER                            9
#define SIN                             10
#define COS                             11
#define WRITE                           12
#define SEMICOLON                       13
#define TIME                            14
#define OF                              15
#define TRACE                           16
#define IDENTIFIER                      17
#define ASSIGN                          18
#define LPAR                            19
#define RPAR                            20
#define LSPAR                           21
#define RSPAR                           22
#define NUMTOKEN                        23
#define TIMETOKEN                       24
#define STRTOKEN                        25
#define BOOLTOKEN                       26
#define NOW                             27
#define NULLTOKEN                       28
#define IS                              29
#define LIST                            30
#define NOT                             31
#define NUMBER                          32
