#define COUNT                            1
#define FIRST                            2
#define WHERE                            3
#define COMMA                            4
#define PLUS                             5
#define MINUS                            6
#define AMPERSAND                        7
#define TIMES                            8
#define DIVIDE                           9
#define GT                              10
#define GTEQ                            11
#define LT                              12
#define LTEQ                            13
#define NEQ                             14
#define POWER                           15
#define SIN                             16
#define COS                             17
#define NOT                             18
#define IS                              19
#define WRITE                           20
#define SEMICOLON                       21
#define TIME                            22
#define OF                              23
#define TRACE                           24
#define IDENTIFIER                      25
#define ASSIGN                          26
#define LPAR                            27
#define RPAR                            28
#define LSPAR                           29
#define RSPAR                           30
#define BOOLTOKEN                       31
#define IT                              32
#define NOW                             33
#define NUMTOKEN                        34
#define NULLTOKEN                       35
#define STRTOKEN                        36
#define TIMETOKEN                       37
#define THEY                            38
#define LIST                            39
#define NUMBER                          40
